---
output: github_document
---


<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  out.width = "100%",
  dpi = 300
)
options(width = 100)
```


# `chatgptscrapeR` : An R package to scrape conversations from publicly shared ChatGPT links

<!-- badges: start -->
<!-- badges: end -->

## Installation


You can install the development version of `chatgptscrapeR` from [GitHub](https://github.com/) with:

```{r, eval = FALSE}
# install.packages("devtools")
devtools::install_github("sonsoleslp/chatgptscrapeR")
```

## Example

Load the library
```{r, message = FALSE}
library("chatgptscrapeR")
library("dplyr")
library("tidyr")
```


Scrape one conversation
```{r, results = FALSE}
# URL of the ChatGPT conversation
url1 <- "https://chatgpt.com/share/c7a912da-5dd3-4e46-9fd7-d777006068ff"
url2 <- "https://chatgpt.com/share/c302f7d3-9d89-4d93-ab89-68c0bfd0b667"

# Scrape the conversation
conversation <- scrape_chatgpt(url1)
select(conversation, order, message.author.role, message.content.parts)
```


```{r, echo = FALSE}
select(conversation, order, message.author.role, message.content.parts) |>
  gt::gt() |>   
  gt::sub_missing(columns = gt::everything(), rows = gt::everything(), missing_text = "---") |> 
  gt::tab_options(table.font.size = 8) |> gt::as_raw_html()
```



Scrape an array of conversations
```{r, results = FALSE}
urls <- c(url1, url2)

# Scrape the conversations
conversation <- scrape_chatgpt(urls)
select(conversation, order, title, message.author.role, message.content.parts)
```


```{r, echo = FALSE}
select(conversation, order, title, message.author.role, message.content.parts) |>
  gt::gt() |>   
  gt::sub_missing(columns = gt::everything(), rows = gt::everything(), missing_text = "---") |> 
  gt::tab_options(table.font.size = 8) |> gt::as_raw_html()
```


Scrape a dataframe containing conversation URLs


```{r, results = FALSE}
df <-  data.frame(user = c("User1", "User2"), 
                  age = c(15, 14),
                  gender = c("M", "F"),
                  url = urls)


conversation <- scrape_chatgpt(df, column = "url") |> 
  filter(message.content.parts != "")

select(conversation, order, user, title, message.author.role, message.content.parts) 
```
 
```{r, echo = FALSE}
select(conversation, order, user, title, message.author.role, message.content.parts) |>
  gt::gt() |>   
  gt::sub_missing(columns = gt::everything(), rows = gt::everything(), missing_text = "---") |> 
  gt::tab_options(table.font.size = 8) |> gt::as_raw_html()
```

